//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.5.0
//     from Assets/Controls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @Controls: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @Controls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""Controls"",
    ""maps"": [
        {
            ""name"": ""CubeFlip"",
            ""id"": ""ad743003-8a10-4341-bc7c-d06965382168"",
            ""actions"": [
                {
                    ""name"": ""Flip"",
                    ""type"": ""Button"",
                    ""id"": ""8d37e3b8-0acb-46cf-bc0b-2f8c8a65b4e9"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""a9f6a3f4-3e4c-4c66-be86-85da04b3cb19"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Flip"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // CubeFlip
        m_CubeFlip = asset.FindActionMap("CubeFlip", throwIfNotFound: true);
        m_CubeFlip_Flip = m_CubeFlip.FindAction("Flip", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // CubeFlip
    private readonly InputActionMap m_CubeFlip;
    private List<ICubeFlipActions> m_CubeFlipActionsCallbackInterfaces = new List<ICubeFlipActions>();
    private readonly InputAction m_CubeFlip_Flip;
    public struct CubeFlipActions
    {
        private @Controls m_Wrapper;
        public CubeFlipActions(@Controls wrapper) { m_Wrapper = wrapper; }
        public InputAction @Flip => m_Wrapper.m_CubeFlip_Flip;
        public InputActionMap Get() { return m_Wrapper.m_CubeFlip; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(CubeFlipActions set) { return set.Get(); }
        public void AddCallbacks(ICubeFlipActions instance)
        {
            if (instance == null || m_Wrapper.m_CubeFlipActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_CubeFlipActionsCallbackInterfaces.Add(instance);
            @Flip.started += instance.OnFlip;
            @Flip.performed += instance.OnFlip;
            @Flip.canceled += instance.OnFlip;
        }

        private void UnregisterCallbacks(ICubeFlipActions instance)
        {
            @Flip.started -= instance.OnFlip;
            @Flip.performed -= instance.OnFlip;
            @Flip.canceled -= instance.OnFlip;
        }

        public void RemoveCallbacks(ICubeFlipActions instance)
        {
            if (m_Wrapper.m_CubeFlipActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(ICubeFlipActions instance)
        {
            foreach (var item in m_Wrapper.m_CubeFlipActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_CubeFlipActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public CubeFlipActions @CubeFlip => new CubeFlipActions(this);
    public interface ICubeFlipActions
    {
        void OnFlip(InputAction.CallbackContext context);
    }
}
